services:
  mlflow:
    image: ubuntu/mlflow:2.1.1_1.0-22.04
    container_name: tracker_mlflow
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - mlflow-data:/mlflow/mlruns
    command: >
      mlflow server
        --backend-store-uri sqlite:///mlflow/mlruns/mlflow.db
        --default-artifact-root /mlflow/mlruns
        --host 0.0.0.0
        --port 5000

  app:
    image: my-mlflow-base:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlflow_deployer
    restart: unless-stopped
    ports:
      - "8080:8080" #expose FastAPI port
    depends_on:
      - mlflow
    command: ["python", "src/mlflow_fastapi_docker/deploy.py"]
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - mlflow-data:/mlflow/mlruns
      - ./data:/app/data

  # Model training service
  train:
    image: my-mlflow-base:latest
    container_name: mlflow_trainer
    depends_on:
      - mlflow
    command: ["python", "src/mlflow_fastapi_docker/train.py"]
    volumes:
      - mlflow-data:/mlflow/mlruns
      - ./data:/app/data
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000

volumes:
  mlflow-data:
