site_name: mlflow-fastapi-docker
repo_url: https://github.com/ruipinto2025/mlflow-fastapi-docker
site_url: https://ruipinto2025.github.io/mlflow-fastapi-docker
site_description: This is a template repository for Python projects that use uv for their dependency management.
site_author: Rui Pinto
edit_uri: edit/main/docs/
repo_name: ruipinto2025/mlflow-fastapi-docker
copyright: Maintained by ruipinto2025</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/mlflow_fastapi_docker"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ruipinto2025/mlflow-fastapi-docker
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/mlflow-fastapi-docker

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
